<a href="https://colab.research.google.com/github/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_10_5_temporal_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# T81-558: Applications of Deep Neural Networks
**Module 10: Time Series in Keras**
* Instructor: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), McKelvey School of Engineering, [Washington University in St. Louis](https://engineering.wustl.edu/Programs/Pages/default.aspx)
* For more information visit the [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

# Module 10 Material

* Part 10.1: Time Series Data Encoding for Deep Learning [[Video]](https://www.youtube.com/watch?v=dMUmHsktl04&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_1_timeseries.ipynb)
* Part 10.2: Programming LSTM with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=wY0dyFgNCgY&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_2_lstm.ipynb)
* Part 10.3: Text Generation with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=6ORnRAz3gnA&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_3_text_generation.ipynb)
* Part 10.4: Image Captioning with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=NmoW_AYWkb4&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_4_captioning.ipynb)
* **Part 10.5: Temporal CNN in Keras and TensorFlow** [[Video]](https://www.youtube.com/watch?v=i390g8acZwk&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_5_temporal_cnn.ipynb)

# Google CoLab Instructions

The following code ensures that Google CoLab is running the correct version of TensorFlow.
  Running the following code will map your GDrive to ```/content/drive```.

In [1]:
try:
    %tensorflow_version 2.x
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Note: not using Google CoLab


# Part 10.5: Temporal CNN in Keras and TensorFlow

Traditionally, Convolutional Neural Networks (CNNs) are used for image classification problems and Long Short Term Memory (LSTM) Networks have been used for time series.  However, recent research has shown CNN's to be very effective at time series problems. 

In [2]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D
import numpy as np

max_features = 4 # 0,1,2,3 (total of 4)
x = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[2],[2],[0]],
    [[0],[0],[0],[0],[3],[3]],
    [[0],[2],[2],[0],[0],[0]],
    [[0],[0],[3],[3],[0],[0]],
    [[0],[0],[0],[0],[1],[1]]
]
x = np.array(x,dtype=np.float32)
y = np.array([1,2,3,2,3,1],dtype=np.int32)

# Convert y2 to dummy variables
y2 = np.zeros((y.shape[0], max_features),dtype=np.float32)
y2[np.arange(y.shape[0]), y] = 1.0
y2 = np.asarray(y2).astype('float32').reshape((-1,1,4))
print(y2)

print('Build model...')
model = Sequential()
model.add(Conv1D(128, kernel_size=x.shape[1], input_shape=(None, 1)))
model.add(Dense(4, activation='sigmoid'))

# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print('Train...')
model.fit(x,y2,epochs=200)
pred = model.predict(x)
predict_classes = np.argmax(pred,axis=1)
print("Predicted classes: {}",predict_classes)
print("Expected classes: {}",predict_classes)

[[[0. 1. 0. 0.]]

 [[0. 0. 1. 0.]]

 [[0. 0. 0. 1.]]

 [[0. 0. 1. 0.]]

 [[0. 0. 0. 1.]]

 [[0. 1. 0. 0.]]]
Build model...
Train...
Train on 6 samples
Epoch 1/200
6/6 [==============================] - 2s 375ms/sample - loss: 0.7119 - accuracy: 0.5000
Epoch 2/200
6/6 [==============================] - 0s 845us/sample - loss: 0.6971 - accuracy: 0.5000
Epoch 3/200
6/6 [==============================] - 0s 674us/sample - loss: 0.6828 - accuracy: 0.4583
Epoch 4/200
6/6 [==============================] - 0s 820us/sample - loss: 0.6690 - accuracy: 0.6667
Epoch 5/200
6/6 [==============================] - 0s 676us/sample - loss: 0.6556 - accuracy: 0.7083
Epoch 6/200
6/6 [==============================] - 0s 664us/sample - loss: 0.6427 - accuracy: 0.7083
Epoch 7/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.6302 - accuracy: 0.7083
Epoch 8/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.6181 - accuracy: 0.7083
Epoch 9/200
6/6 [============================

6/6 [==============================] - 0s 1ms/sample - loss: 0.2781 - accuracy: 0.8750
Epoch 82/200
6/6 [==============================] - 0s 666us/sample - loss: 0.2758 - accuracy: 0.8750
Epoch 83/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.2736 - accuracy: 0.8750
Epoch 84/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.2714 - accuracy: 0.8750
Epoch 85/200
6/6 [==============================] - 0s 667us/sample - loss: 0.2692 - accuracy: 0.8750
Epoch 86/200
6/6 [==============================] - 0s 669us/sample - loss: 0.2670 - accuracy: 0.8750
Epoch 87/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.2649 - accuracy: 0.8750
Epoch 88/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.2628 - accuracy: 0.8750
Epoch 89/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.2607 - accuracy: 0.8750
Epoch 90/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.2587 - accuracy: 0.8750
Epoch 9

Epoch 162/200
6/6 [==============================] - 0s 663us/sample - loss: 0.1555 - accuracy: 0.9583
Epoch 163/200
6/6 [==============================] - 0s 670us/sample - loss: 0.1544 - accuracy: 0.9583
Epoch 164/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.1533 - accuracy: 0.9583
Epoch 165/200
6/6 [==============================] - 0s 667us/sample - loss: 0.1523 - accuracy: 0.9583
Epoch 166/200
6/6 [==============================] - 0s 667us/sample - loss: 0.1512 - accuracy: 0.9583
Epoch 167/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.1501 - accuracy: 0.9583
Epoch 168/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.1490 - accuracy: 1.0000
Epoch 169/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.1479 - accuracy: 1.0000
Epoch 170/200
6/6 [==============================] - 0s 667us/sample - loss: 0.1469 - accuracy: 1.0000
Epoch 171/200
6/6 [==============================] - 0s 898us/sample - loss: 0.14

In [3]:
def runit(model, inp):
    inp = np.array(inp,dtype=np.float32)
    pred = model.predict(inp)
    return np.argmax(pred[0])

print( runit( model, [[[0],[1],[1],[0],[0],[0]]] ))


1


### Sun Spots Example - CNN

An example of RNN regression to predict sunspots.  The data files needed for this example can be found at the following location.

* [Sunspot Data Files](http://www.sidc.be/silso/datafiles#total)
* [Download Daily Sunspots](http://www.sidc.be/silso/INFO/sndtotcsv.php) - 1/1/1818 to now.

The following code is used to load the sunspot file:


In [4]:
import pandas as pd
import os

# Replacce the following path with your own file. It can be downloaded from:
# http://www.sidc.be/silso/INFO/sndtotcsv.php
path = "./data/"
    
filename = os.path.join(path,"SN_d_tot_V2.0.csv")    
names = ['year', 'month', 'day', 'dec_year', 'sn_value' , 
         'sn_error', 'obs_num']
df = pd.read_csv(filename,sep=';',header=None,names=names,
                 na_values=['-1'], index_col=False)

print("Starting file:")
print(df[0:10])

print("Ending file:")
print(df[-10:])

Starting file:
   year  month  day  dec_year  sn_value  sn_error  obs_num
0  1818      1    1  1818.001        -1       NaN        0
1  1818      1    2  1818.004        -1       NaN        0
2  1818      1    3  1818.007        -1       NaN        0
3  1818      1    4  1818.010        -1       NaN        0
4  1818      1    5  1818.012        -1       NaN        0
5  1818      1    6  1818.015        -1       NaN        0
6  1818      1    7  1818.018        -1       NaN        0
7  1818      1    8  1818.021        65      10.2        1
8  1818      1    9  1818.023        -1       NaN        0
9  1818      1   10  1818.026        -1       NaN        0
Ending file:
       year  month  day  dec_year  sn_value  sn_error  obs_num
73769  2019     12   22  2019.974         0       0.0       17
73770  2019     12   23  2019.977         0       0.0       24
73771  2019     12   24  2019.979        16       1.0       10
73772  2019     12   25  2019.982        23       2.2        7
73773  2

As you can see, there is quite a bit of missing data near the end of the file.  We would like to find the starting index where the missing data no longer occurs.  This is somewhat sloppy, it would be better to find a use for the data between missing values.  However, the point of this example is show how to use LSTM with a somewhat simple time-series.

In [5]:
start_id = max(df[df['obs_num'] == 0].index.tolist())+1  # Find the last zero and move one beyond
print(start_id)
df = df[start_id:] # Trim the rows that have missing observations

11314


In [6]:
df['sn_value'] = df['sn_value'].astype(float)
df_train = df[df['year']<2000]
df_test = df[df['year']>=2000]

spots_train = df_train['sn_value'].tolist()
spots_test = df_test['sn_value'].tolist()

print("Training set has {} observations.".format(len(spots_train)))
print("Test set has {} observations.".format(len(spots_test)))

Training set has 55160 observations.
Test set has 7305 observations.


In [7]:
import numpy as np

def to_sequences(seq_size, obs):
    x = []
    y = []

    for i in range(len(obs)-SEQUENCE_SIZE-1):
        #print(i)
        window = obs[i:(i+SEQUENCE_SIZE)]
        after_window = obs[i+SEQUENCE_SIZE]
        window = [[x] for x in window]
        #print("{} - {}".format(window,after_window))
        x.append(window)
        y.append(after_window)
        
    return np.array(x),np.array(y)
    
    
SEQUENCE_SIZE = 25
x_train,y_train = to_sequences(SEQUENCE_SIZE,spots_train)
x_test,y_test = to_sequences(SEQUENCE_SIZE,spots_test)

print("Shape of training set: {}".format(x_train.shape))
print("Shape of test set: {}".format(x_test.shape))

Shape of training set: (55134, 25, 1)
Shape of test set: (7279, 25, 1)


In [8]:
x_train

array([[[353.],
        [240.],
        [275.],
        ...,
        [270.],
        [289.],
        [308.]],

       [[240.],
        [275.],
        [352.],
        ...,
        [289.],
        [308.],
        [327.]],

       [[275.],
        [352.],
        [268.],
        ...,
        [308.],
        [327.],
        [323.]],

       ...,

       [[ 97.],
        [ 79.],
        [ 70.],
        ...,
        [128.],
        [116.],
        [ 95.]],

       [[ 79.],
        [ 70.],
        [ 87.],
        ...,
        [116.],
        [ 95.],
        [ 85.]],

       [[ 70.],
        [ 87.],
        [ 81.],
        ...,
        [ 95.],
        [ 85.],
        [103.]]])

In [9]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, Dropout, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np

print('Build model...')
model = Sequential()
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', 
                 input_shape=(SEQUENCE_SIZE,1)))
model.add(Conv1D(filters=32, kernel_size=3, activation='relu'))
model.add(Dropout(0.2))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=50, 
                        verbose=1, mode='auto', restore_best_weights=True)
print('Train...')

model.fit(x_train,y_train,validation_data=(x_test,y_test),
          callbacks=[monitor],verbose=2,epochs=1000)

Build model...
Train...
Train on 55134 samples, validate on 7279 samples
Epoch 1/1000
55134/55134 - 8s - loss: 1052.7906 - val_loss: 820.0160
Epoch 2/1000
55134/55134 - 6s - loss: 927.8404 - val_loss: 680.1245
Epoch 3/1000
55134/55134 - 6s - loss: 908.5605 - val_loss: 534.7326
Epoch 4/1000
55134/55134 - 6s - loss: 905.8087 - val_loss: 511.2069
Epoch 5/1000
55134/55134 - 6s - loss: 896.8750 - val_loss: 565.8011
Epoch 6/1000
55134/55134 - 6s - loss: 893.1291 - val_loss: 665.3159
Epoch 7/1000
55134/55134 - 6s - loss: 882.7558 - val_loss: 627.1734
Epoch 8/1000
55134/55134 - 6s - loss: 876.5515 - val_loss: 594.8509
Epoch 9/1000
55134/55134 - 6s - loss: 877.4717 - val_loss: 611.2122
Epoch 10/1000
55134/55134 - 6s - loss: 868.6766 - val_loss: 568.8607
Epoch 11/1000
55134/55134 - 6s - loss: 871.7290 - val_loss: 513.9120
Epoch 12/1000
55134/55134 - 6s - loss: 864.6839 - val_loss: 763.3029
Epoch 13/1000
55134/55134 - 6s - loss: 867.9729 - val_loss: 672.1772
Epoch 14/1000
55134/55134 - 6s - loss:

In [10]:
from sklearn import metrics

# from sklearn import metrics
pred = model.predict(x_test)
score = np.sqrt(metrics.mean_squared_error(pred.flatten(),y_test))
print("Score (RMSE): {}".format(score))

Score (RMSE): 20.432323474625225
