# T81-558: Applications of Deep Neural Networks
**Module 10: Time Series in Keras**
* Instructor: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), McKelvey School of Engineering, [Washington University in St. Louis](https://engineering.wustl.edu/Programs/Pages/default.aspx)
* For more information visit the [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

# Module 10 Material

* Part 10.1: Time Series Data Encoding for Deep Learning [[Video]]() [[Notebook]](t81_558_class_10_1_timeseries.ipynb)
* Part 10.2: Programming LSTM with Keras and TensorFlow [[Video]]() [[Notebook]](t81_558_class_10_2_lstm.ipynb)
* Part 10.3: Text Generation with Keras and TensorFlow [[Video]]() [[Notebook]](t81_558_class_10_3_text_generation.ipynb)
* Part 10.4: Image Captioning with Keras and TensorFlow [[Video]]() [[Notebook]](t81_558_class_10_4_captioning.ipynb)
* **Part 10.5: Temporal CNN in Keras and TensorFlow** [[Video]]() [[Notebook]](t81_558_class_10_5_temporal_cnn.ipynb)

# Part 10.5: Temporal CNN in Keras and TensorFlow

Traditionally, Convolutional Neural Networks (CNNs) are used for image classification problems and Long Short Term Memory (LSTM) Networks have been used for time series.  However, recent research has shown CNN's to be very effective at time series problems. 

In [8]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D
import numpy as np

max_features = 4 # 0,1,2,3 (total of 4)
x = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[2],[2],[0]],
    [[0],[0],[0],[0],[3],[3]],
    [[0],[2],[2],[0],[0],[0]],
    [[0],[0],[3],[3],[0],[0]],
    [[0],[0],[0],[0],[1],[1]]
]
x = np.array(x,dtype=np.float32)
y = np.array([1,2,3,2,3,1],dtype=np.int32)

# Convert y2 to dummy variables
y2 = np.zeros((y.shape[0], max_features),dtype=np.float32)
y2[np.arange(y.shape[0]), y] = 1.0
print(y2)

print('Build model...')
model = Sequential()
model.add(Conv1D(128, kernel_size=x.shape[1], input_shape=(None, 1)))
model.add(Dense(4, activation='sigmoid'))

# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print('Train...')
model.fit(x,y2,epochs=200)
pred = model.predict(x)
predict_classes = np.argmax(pred,axis=1)
print("Predicted classes: {}",predict_classes)
print("Expected classes: {}",predict_classes)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
Build model...
Train...
Epoch 1/200
6/6 [==============================] - 0s 21ms/sample - loss: 0.6813 - accuracy: 0.5694
Epoch 2/200
6/6 [==============================] - 0s 291us/sample - loss: 0.6702 - accuracy: 0.5694
Epoch 3/200
6/6 [==============================] - 0s 281us/sample - loss: 0.6595 - accuracy: 0.6667
Epoch 4/200
6/6 [==============================] - 0s 327us/sample - loss: 0.6493 - accuracy: 0.6806
Epoch 5/200
6/6 [==============================] - 0s 329us/sample - loss: 0.6395 - accuracy: 0.6806
Epoch 6/200
6/6 [==============================] - 0s 286us/sample - loss: 0.6303 - accuracy: 0.6944
Epoch 7/200
6/6 [==============================] - 0s 312us/sample - loss: 0.6215 - accuracy: 0.7083
Epoch 8/200
6/6 [==============================] - 0s 314us/sample - loss: 0.6132 - accuracy: 0.7083
Epoch 9/200
6/6 [==============================] - 0s 366us/sample - loss: 0.6

Epoch 81/200
6/6 [==============================] - 0s 377us/sample - loss: 0.4865 - accuracy: 0.7500
Epoch 82/200
6/6 [==============================] - 0s 415us/sample - loss: 0.4863 - accuracy: 0.7500
Epoch 83/200
6/6 [==============================] - 0s 332us/sample - loss: 0.4862 - accuracy: 0.7500
Epoch 84/200
6/6 [==============================] - 0s 406us/sample - loss: 0.4860 - accuracy: 0.7500
Epoch 85/200
6/6 [==============================] - 0s 362us/sample - loss: 0.4859 - accuracy: 0.7500
Epoch 86/200
6/6 [==============================] - 0s 341us/sample - loss: 0.4858 - accuracy: 0.7500
Epoch 87/200
6/6 [==============================] - 0s 409us/sample - loss: 0.4856 - accuracy: 0.7500
Epoch 88/200
6/6 [==============================] - 0s 446us/sample - loss: 0.4855 - accuracy: 0.7500
Epoch 89/200
6/6 [==============================] - 0s 477us/sample - loss: 0.4854 - accuracy: 0.7500
Epoch 90/200
6/6 [==============================] - 0s 322us/sample - loss: 0.4852

Epoch 161/200
6/6 [==============================] - 0s 313us/sample - loss: 0.4806 - accuracy: 0.7500
Epoch 162/200
6/6 [==============================] - 0s 441us/sample - loss: 0.4806 - accuracy: 0.7500
Epoch 163/200
6/6 [==============================] - 0s 376us/sample - loss: 0.4806 - accuracy: 0.7500
Epoch 164/200
6/6 [==============================] - 0s 310us/sample - loss: 0.4805 - accuracy: 0.7500
Epoch 165/200
6/6 [==============================] - 0s 311us/sample - loss: 0.4805 - accuracy: 0.7500
Epoch 166/200
6/6 [==============================] - 0s 329us/sample - loss: 0.4805 - accuracy: 0.7500
Epoch 167/200
6/6 [==============================] - 0s 349us/sample - loss: 0.4804 - accuracy: 0.7500
Epoch 168/200
6/6 [==============================] - 0s 466us/sample - loss: 0.4804 - accuracy: 0.7500
Epoch 169/200
6/6 [==============================] - 0s 459us/sample - loss: 0.4804 - accuracy: 0.7500
Epoch 170/200
6/6 [==============================] - 0s 689us/sample - lo

In [10]:
def runit(model, inp):
    inp = np.array(inp,dtype=np.float32)
    pred = model.predict(inp)
    return np.argmax(pred[0])

print( runit( model, [[[0],[1],[1],[0],[0],[0]]] ))


1


### Sun Spots Example - CNN

An example of RNN regression to predict sunspots.  The data files needed for this example can be found at the following location.

* [Sunspot Data Files](http://www.sidc.be/silso/datafiles#total)
* [Download Daily Sunspots](http://www.sidc.be/silso/INFO/sndtotcsv.php) - 1/1/1818 to now.

The following code is used to load the sunspot file:


In [11]:
import pandas as pd
import os

# Replacce the following path with your own file. It can be downloaded from:
# http://www.sidc.be/silso/INFO/sndtotcsv.php
path = "./data/"
    
filename = os.path.join(path,"SN_d_tot_V2.0.csv")    
names = ['year', 'month', 'day', 'dec_year', 'sn_value' , 'sn_error', 'obs_num']
df = pd.read_csv(filename,sep=';',header=None,names=names,na_values=['-1'], index_col=False)

print("Starting file:")
print(df[0:10])

print("Ending file:")
print(df[-10:])

Starting file:
   year  month  day  dec_year  sn_value  sn_error  obs_num
0  1818      1    1  1818.001        -1       NaN        0
1  1818      1    2  1818.004        -1       NaN        0
2  1818      1    3  1818.007        -1       NaN        0
3  1818      1    4  1818.010        -1       NaN        0
4  1818      1    5  1818.012        -1       NaN        0
5  1818      1    6  1818.015        -1       NaN        0
6  1818      1    7  1818.018        -1       NaN        0
7  1818      1    8  1818.021        65      10.2        1
8  1818      1    9  1818.023        -1       NaN        0
9  1818      1   10  1818.026        -1       NaN        0
Ending file:
       year  month  day  dec_year  sn_value  sn_error  obs_num
73373  2018     11   21  2018.889         0       0.0       31
73374  2018     11   22  2018.892         0       0.0       15
73375  2018     11   23  2018.895         0       0.0       22
73376  2018     11   24  2018.897        15       2.7        8
73377  2

As you can see, there is quite a bit of missing data near the end of the file.  We would like to find the starting index where the missing data no longer occurs.  This is somewhat sloppy, it would be better to find a use for the data between missing values.  However, the point of this example is show how to use LSTM with a somewhat simple time-series.

In [12]:
start_id = max(df[df['obs_num'] == 0].index.tolist())+1  # Find the last zero and move one beyond
print(start_id)
df = df[start_id:] # Trim the rows that have missing observations

11314


In [13]:
df_train = df[df['year']<2000]
df_test = df[df['year']>=2000]

spots_train = df_train['sn_value'].tolist()
spots_test = df_test['sn_value'].tolist()

print("Training set has {} observations.".format(len(spots_train)))
print("Test set has {} observations.".format(len(spots_test)))

Training set has 55160 observations.
Test set has 6909 observations.


In [14]:
import numpy as np

def to_sequences(seq_size, obs):
    x = []
    y = []

    for i in range(len(obs)-SEQUENCE_SIZE-1):
        #print(i)
        window = obs[i:(i+SEQUENCE_SIZE)]
        after_window = obs[i+SEQUENCE_SIZE]
        window = [[x] for x in window]
        #print("{} - {}".format(window,after_window))
        x.append(window)
        y.append(after_window)
        
    return np.array(x),np.array(y)
    
    
SEQUENCE_SIZE = 25
x_train,y_train = to_sequences(SEQUENCE_SIZE,spots_train)
x_test,y_test = to_sequences(SEQUENCE_SIZE,spots_test)

print("Shape of training set: {}".format(x_train.shape))
print("Shape of test set: {}".format(x_test.shape))

Shape of training set: (55134, 25, 1)
Shape of test set: (6883, 25, 1)


In [15]:
x_train

array([[[353],
        [240],
        [275],
        ...,
        [270],
        [289],
        [308]],

       [[240],
        [275],
        [352],
        ...,
        [289],
        [308],
        [327]],

       [[275],
        [352],
        [268],
        ...,
        [308],
        [327],
        [323]],

       ...,

       [[ 97],
        [ 79],
        [ 70],
        ...,
        [128],
        [116],
        [ 95]],

       [[ 79],
        [ 70],
        [ 87],
        ...,
        [116],
        [ 95],
        [ 85]],

       [[ 70],
        [ 87],
        [ 81],
        ...,
        [ 95],
        [ 85],
        [103]]])

In [16]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, Dropout, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np

print('Build model...')
model = Sequential()
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(SEQUENCE_SIZE,1)))
model.add(Conv1D(filters=32, kernel_size=3, activation='relu'))
model.add(Dropout(0.2))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=50, verbose=1, mode='auto', restore_best_weights=True)
print('Train...')

model.fit(x_train,y_train,validation_data=(x_test,y_test),callbacks=[monitor],verbose=2,epochs=1000)

Build model...
Train...
Train on 55134 samples, validate on 6883 samples
Epoch 1/1000
55134/55134 - 4s - loss: 1065.8916 - val_loss: 750.3109
Epoch 2/1000
55134/55134 - 4s - loss: 928.7273 - val_loss: 543.4265
Epoch 3/1000
55134/55134 - 4s - loss: 903.6136 - val_loss: 785.8058
Epoch 4/1000
55134/55134 - 4s - loss: 894.3934 - val_loss: 540.8068
Epoch 5/1000
55134/55134 - 4s - loss: 880.9777 - val_loss: 890.2584
Epoch 6/1000
55134/55134 - 4s - loss: 883.5528 - val_loss: 648.2149
Epoch 7/1000
55134/55134 - 4s - loss: 874.5668 - val_loss: 492.5848
Epoch 8/1000
55134/55134 - 4s - loss: 873.1542 - val_loss: 563.4214
Epoch 9/1000
55134/55134 - 4s - loss: 870.7498 - val_loss: 487.6851
Epoch 10/1000
55134/55134 - 4s - loss: 868.0045 - val_loss: 660.2686
Epoch 11/1000
55134/55134 - 4s - loss: 862.7693 - val_loss: 562.7063
Epoch 12/1000
55134/55134 - 4s - loss: 859.1641 - val_loss: 519.7549
Epoch 13/1000
55134/55134 - 4s - loss: 854.3423 - val_loss: 597.0621
Epoch 14/1000
55134/55134 - 4s - loss:

In [19]:
from sklearn import metrics

# from sklearn import metrics
pred = model.predict(x_test)
score = np.sqrt(metrics.mean_squared_error(pred.flatten(),y_test))
print("Score (RMSE): {}".format(score))

Score (RMSE): 21.38689754965083
