# T81-558: Applications of Deep Neural Networks
**Module 10: Time Series in Keras**
* Instructor: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), McKelvey School of Engineering, [Washington University in St. Louis](https://engineering.wustl.edu/Programs/Pages/default.aspx)
* For more information visit the [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

# Module 10 Material

* Part 10.1: Time Series Data Encoding for Deep Learning [[Video]](https://www.youtube.com/watch?v=dMUmHsktl04&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_1_timeseries.ipynb)
* Part 10.2: Programming LSTM with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=wY0dyFgNCgY&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_2_lstm.ipynb)
* Part 10.3: Text Generation with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=6ORnRAz3gnA&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_3_text_generation.ipynb)
* Part 10.4: Image Captioning with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=NmoW_AYWkb4&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_4_captioning.ipynb)
* **Part 10.5: Temporal CNN in Keras and TensorFlow** [[Video]](https://www.youtube.com/watch?v=i390g8acZwk&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_5_temporal_cnn.ipynb)

# Part 10.5: Temporal CNN in Keras and TensorFlow

Traditionally, Convolutional Neural Networks (CNNs) are used for image classification problems and Long Short Term Memory (LSTM) Networks have been used for time series.  However, recent research has shown CNN's to be very effective at time series problems. 

In [1]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D
import numpy as np

max_features = 4 # 0,1,2,3 (total of 4)
x = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[2],[2],[0]],
    [[0],[0],[0],[0],[3],[3]],
    [[0],[2],[2],[0],[0],[0]],
    [[0],[0],[3],[3],[0],[0]],
    [[0],[0],[0],[0],[1],[1]]
]
x = np.array(x,dtype=np.float32)
y = np.array([1,2,3,2,3,1],dtype=np.int32)

# Convert y2 to dummy variables
y2 = np.zeros((y.shape[0], max_features),dtype=np.float32)
y2[np.arange(y.shape[0]), y] = 1.0
print(y2)

print('Build model...')
model = Sequential()
model.add(Conv1D(128, kernel_size=x.shape[1], input_shape=(None, 1)))
model.add(Dense(4, activation='sigmoid'))

# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print('Train...')
model.fit(x,y2,epochs=200)
pred = model.predict(x)
predict_classes = np.argmax(pred,axis=1)
print("Predicted classes: {}",predict_classes)
print("Expected classes: {}",predict_classes)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
Build model...
Train...


W0820 09:12:45.687239 140736216040320 deprecation.py:323] From /Users/jheaton/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 6 samples
Epoch 1/200
6/6 [==============================] - 0s 20ms/sample - loss: 0.7007 - accuracy: 0.4583
Epoch 2/200
6/6 [==============================] - 0s 219us/sample - loss: 0.6882 - accuracy: 0.5278
Epoch 3/200
6/6 [==============================] - 0s 290us/sample - loss: 0.6763 - accuracy: 0.5278
Epoch 4/200
6/6 [==============================] - 0s 252us/sample - loss: 0.6649 - accuracy: 0.6389
Epoch 5/200
6/6 [==============================] - 0s 265us/sample - loss: 0.6540 - accuracy: 0.7083
Epoch 6/200
6/6 [==============================] - 0s 252us/sample - loss: 0.6437 - accuracy: 0.7083
Epoch 7/200
6/6 [==============================] - 0s 325us/sample - loss: 0.6340 - accuracy: 0.7500
Epoch 8/200
6/6 [==============================] - 0s 395us/sample - loss: 0.6247 - accuracy: 0.7500
Epoch 9/200
6/6 [==============================] - 0s 316us/sample - loss: 0.6160 - accuracy: 0.7500
Epoch 10/200
6/6 [==============================] - 0s 310us/sample - los

Epoch 82/200
6/6 [==============================] - 0s 579us/sample - loss: 0.4872 - accuracy: 0.7500
Epoch 83/200
6/6 [==============================] - 0s 665us/sample - loss: 0.4870 - accuracy: 0.7500
Epoch 84/200
6/6 [==============================] - 0s 462us/sample - loss: 0.4868 - accuracy: 0.7500
Epoch 85/200
6/6 [==============================] - 0s 412us/sample - loss: 0.4867 - accuracy: 0.7500
Epoch 86/200
6/6 [==============================] - 0s 369us/sample - loss: 0.4865 - accuracy: 0.7500
Epoch 87/200
6/6 [==============================] - 0s 370us/sample - loss: 0.4864 - accuracy: 0.7500
Epoch 88/200
6/6 [==============================] - 0s 274us/sample - loss: 0.4862 - accuracy: 0.7500
Epoch 89/200
6/6 [==============================] - 0s 399us/sample - loss: 0.4861 - accuracy: 0.7500
Epoch 90/200
6/6 [==============================] - 0s 384us/sample - loss: 0.4859 - accuracy: 0.7500
Epoch 91/200
6/6 [==============================] - 0s 323us/sample - loss: 0.4858

Epoch 162/200
6/6 [==============================] - 0s 317us/sample - loss: 0.4809 - accuracy: 0.7500
Epoch 163/200
6/6 [==============================] - 0s 388us/sample - loss: 0.4809 - accuracy: 0.7500
Epoch 164/200
6/6 [==============================] - 0s 308us/sample - loss: 0.4808 - accuracy: 0.7500
Epoch 165/200
6/6 [==============================] - 0s 343us/sample - loss: 0.4808 - accuracy: 0.7500
Epoch 166/200
6/6 [==============================] - 0s 334us/sample - loss: 0.4808 - accuracy: 0.7500
Epoch 167/200
6/6 [==============================] - 0s 302us/sample - loss: 0.4807 - accuracy: 0.7500
Epoch 168/200
6/6 [==============================] - 0s 326us/sample - loss: 0.4807 - accuracy: 0.7500
Epoch 169/200
6/6 [==============================] - 0s 283us/sample - loss: 0.4807 - accuracy: 0.7500
Epoch 170/200
6/6 [==============================] - 0s 285us/sample - loss: 0.4806 - accuracy: 0.7500
Epoch 171/200
6/6 [==============================] - 0s 353us/sample - lo

In [2]:
def runit(model, inp):
    inp = np.array(inp,dtype=np.float32)
    pred = model.predict(inp)
    return np.argmax(pred[0])

print( runit( model, [[[0],[1],[1],[0],[0],[0]]] ))


2


### Sun Spots Example - CNN

An example of RNN regression to predict sunspots.  The data files needed for this example can be found at the following location.

* [Sunspot Data Files](http://www.sidc.be/silso/datafiles#total)
* [Download Daily Sunspots](http://www.sidc.be/silso/INFO/sndtotcsv.php) - 1/1/1818 to now.

The following code is used to load the sunspot file:


In [3]:
import pandas as pd
import os

# Replacce the following path with your own file. It can be downloaded from:
# http://www.sidc.be/silso/INFO/sndtotcsv.php
path = "./data/"
    
filename = os.path.join(path,"SN_d_tot_V2.0.csv")    
names = ['year', 'month', 'day', 'dec_year', 'sn_value' , 'sn_error', 'obs_num']
df = pd.read_csv(filename,sep=';',header=None,names=names,na_values=['-1'], index_col=False)

print("Starting file:")
print(df[0:10])

print("Ending file:")
print(df[-10:])

Starting file:
   year  month  day  dec_year  sn_value  sn_error  obs_num
0  1818      1    1  1818.001        -1       NaN        0
1  1818      1    2  1818.004        -1       NaN        0
2  1818      1    3  1818.007        -1       NaN        0
3  1818      1    4  1818.010        -1       NaN        0
4  1818      1    5  1818.012        -1       NaN        0
5  1818      1    6  1818.015        -1       NaN        0
6  1818      1    7  1818.018        -1       NaN        0
7  1818      1    8  1818.021        65      10.2        1
8  1818      1    9  1818.023        -1       NaN        0
9  1818      1   10  1818.026        -1       NaN        0
Ending file:
       year  month  day  dec_year  sn_value  sn_error  obs_num
73616  2019      7   22  2019.555         8       0.8       25
73617  2019      7   23  2019.558         0       0.0       39
73618  2019      7   24  2019.560         0       0.0       46
73619  2019      7   25  2019.563         0       0.0       45
73620  2

As you can see, there is quite a bit of missing data near the end of the file.  We would like to find the starting index where the missing data no longer occurs.  This is somewhat sloppy, it would be better to find a use for the data between missing values.  However, the point of this example is show how to use LSTM with a somewhat simple time-series.

In [4]:
start_id = max(df[df['obs_num'] == 0].index.tolist())+1  # Find the last zero and move one beyond
print(start_id)
df = df[start_id:] # Trim the rows that have missing observations

11314


In [5]:
df_train = df[df['year']<2000]
df_test = df[df['year']>=2000]

spots_train = df_train['sn_value'].tolist()
spots_test = df_test['sn_value'].tolist()

print("Training set has {} observations.".format(len(spots_train)))
print("Test set has {} observations.".format(len(spots_test)))

Training set has 55160 observations.
Test set has 7152 observations.


In [6]:
import numpy as np

def to_sequences(seq_size, obs):
    x = []
    y = []

    for i in range(len(obs)-SEQUENCE_SIZE-1):
        #print(i)
        window = obs[i:(i+SEQUENCE_SIZE)]
        after_window = obs[i+SEQUENCE_SIZE]
        window = [[x] for x in window]
        #print("{} - {}".format(window,after_window))
        x.append(window)
        y.append(after_window)
        
    return np.array(x),np.array(y)
    
    
SEQUENCE_SIZE = 25
x_train,y_train = to_sequences(SEQUENCE_SIZE,spots_train)
x_test,y_test = to_sequences(SEQUENCE_SIZE,spots_test)

print("Shape of training set: {}".format(x_train.shape))
print("Shape of test set: {}".format(x_test.shape))

Shape of training set: (55134, 25, 1)
Shape of test set: (7126, 25, 1)


In [7]:
x_train

array([[[353],
        [240],
        [275],
        ...,
        [270],
        [289],
        [308]],

       [[240],
        [275],
        [352],
        ...,
        [289],
        [308],
        [327]],

       [[275],
        [352],
        [268],
        ...,
        [308],
        [327],
        [323]],

       ...,

       [[ 97],
        [ 79],
        [ 70],
        ...,
        [128],
        [116],
        [ 95]],

       [[ 79],
        [ 70],
        [ 87],
        ...,
        [116],
        [ 95],
        [ 85]],

       [[ 70],
        [ 87],
        [ 81],
        ...,
        [ 95],
        [ 85],
        [103]]])

In [8]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, Dropout, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np

print('Build model...')
model = Sequential()
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(SEQUENCE_SIZE,1)))
model.add(Conv1D(filters=32, kernel_size=3, activation='relu'))
model.add(Dropout(0.2))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=50, verbose=1, mode='auto', restore_best_weights=True)
print('Train...')

model.fit(x_train,y_train,validation_data=(x_test,y_test),callbacks=[monitor],verbose=2,epochs=1000)

Build model...
Train...
Train on 55134 samples, validate on 7126 samples
Epoch 1/1000
55134/55134 - 4s - loss: 1066.3207 - val_loss: 662.3279
Epoch 2/1000
55134/55134 - 4s - loss: 919.5086 - val_loss: 758.8296
Epoch 3/1000
55134/55134 - 4s - loss: 903.9341 - val_loss: 675.9912
Epoch 4/1000
55134/55134 - 4s - loss: 901.2349 - val_loss: 664.1927
Epoch 5/1000
55134/55134 - 4s - loss: 884.1174 - val_loss: 537.8667
Epoch 6/1000
55134/55134 - 4s - loss: 885.5698 - val_loss: 658.6137
Epoch 7/1000
55134/55134 - 4s - loss: 882.8827 - val_loss: 667.2707
Epoch 8/1000
55134/55134 - 5s - loss: 874.7731 - val_loss: 480.2243
Epoch 9/1000
55134/55134 - 5s - loss: 874.8989 - val_loss: 599.1845
Epoch 10/1000
55134/55134 - 4s - loss: 865.9352 - val_loss: 605.0286
Epoch 11/1000
55134/55134 - 5s - loss: 864.1161 - val_loss: 614.2303
Epoch 12/1000
55134/55134 - 4s - loss: 858.3618 - val_loss: 671.9098
Epoch 13/1000
55134/55134 - 4s - loss: 857.7733 - val_loss: 483.9761
Epoch 14/1000
55134/55134 - 4s - loss:

Epoch 119/1000
55134/55134 - 5s - loss: 726.5970 - val_loss: 528.7048
Epoch 120/1000
55134/55134 - 5s - loss: 724.4342 - val_loss: 566.6720
Epoch 121/1000
55134/55134 - 5s - loss: 729.4925 - val_loss: 509.8670
Epoch 122/1000
55134/55134 - 5s - loss: 730.2105 - val_loss: 617.2604
Epoch 123/1000
55134/55134 - 5s - loss: 730.8583 - val_loss: 577.1652
Epoch 124/1000
55134/55134 - 5s - loss: 728.7460 - val_loss: 539.5504
Epoch 125/1000
55134/55134 - 5s - loss: 726.8272 - val_loss: 550.7886
Epoch 126/1000
55134/55134 - 5s - loss: 725.8271 - val_loss: 453.5865
Epoch 127/1000
55134/55134 - 5s - loss: 719.9203 - val_loss: 536.5451
Epoch 128/1000
55134/55134 - 5s - loss: 723.1689 - val_loss: 540.5680
Epoch 129/1000
55134/55134 - 5s - loss: 717.3914 - val_loss: 570.6946
Epoch 130/1000
55134/55134 - 5s - loss: 722.7900 - val_loss: 489.6232
Epoch 131/1000
55134/55134 - 5s - loss: 724.1328 - val_loss: 583.4160
Epoch 132/1000
55134/55134 - 5s - loss: 724.7606 - val_loss: 494.0735
Epoch 133/1000
55134

In [9]:
from sklearn import metrics

# from sklearn import metrics
pred = model.predict(x_test)
score = np.sqrt(metrics.mean_squared_error(pred.flatten(),y_test))
print("Score (RMSE): {}".format(score))

Score (RMSE): 21.25857311904512
