<a href="https://colab.research.google.com/github/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_10_5_temporal_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# T81-558: Applications of Deep Neural Networks
**Module 10: Time Series in Keras**
* Instructor: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), McKelvey School of Engineering, [Washington University in St. Louis](https://engineering.wustl.edu/Programs/Pages/default.aspx)
* For more information visit the [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

# Module 10 Material

* Part 10.1: Time Series Data Encoding for Deep Learning [[Video]](https://www.youtube.com/watch?v=dMUmHsktl04&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_1_timeseries.ipynb)
* Part 10.2: Programming LSTM with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=wY0dyFgNCgY&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_2_lstm.ipynb)
* Part 10.3: Text Generation with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=6ORnRAz3gnA&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_3_text_generation.ipynb)
* Part 10.4: Image Captioning with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=NmoW_AYWkb4&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_4_captioning.ipynb)
* **Part 10.5: Temporal CNN in Keras and TensorFlow** [[Video]](https://www.youtube.com/watch?v=i390g8acZwk&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_5_temporal_cnn.ipynb)

# Google CoLab Instructions

The following code ensures that Google CoLab is running the correct version of TensorFlow.
  Running the following code will map your GDrive to ```/content/drive```.

In [1]:
try:
    %tensorflow_version 2.x
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

# Part 10.5: Temporal CNN in Keras and TensorFlow

Traditionally, we use Convolutional Neural Networks (CNNs) for image classification problems, and Long Short Term Memory (LSTM) networks for time series.  However, recent research has shown CNN's to be very useful at time series problems. 

In [2]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D
import numpy as np

max_features = 4 # 0,1,2,3 (total of 4)
x = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[2],[2],[0]],
    [[0],[0],[0],[0],[3],[3]],
    [[0],[2],[2],[0],[0],[0]],
    [[0],[0],[3],[3],[0],[0]],
    [[0],[0],[0],[0],[1],[1]]
]
x = np.array(x,dtype=np.float32)
y = np.array([1,2,3,2,3,1],dtype=np.int32)

# Convert y2 to dummy variables
y2 = np.zeros((y.shape[0], max_features),dtype=np.float32)
y2[np.arange(y.shape[0]), y] = 1.0
y2 = np.asarray(y2).astype('float32').reshape((-1,1,4))
print(y2)

print('Build model...')
model = Sequential()
model.add(Conv1D(128, kernel_size=x.shape[1], input_shape=(None, 1)))
model.add(Dense(4, activation='sigmoid'))

# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print('Train...')
model.fit(x,y2,epochs=200)
pred = model.predict(x)
predict_classes = np.argmax(pred,axis=1)
print("Predicted classes: {}",predict_classes)
print("Expected classes: {}",predict_classes)

[[[0. 1. 0. 0.]]

 [[0. 0. 1. 0.]]

 [[0. 0. 0. 1.]]

 [[0. 0. 1. 0.]]

 [[0. 0. 0. 1.]]

 [[0. 1. 0. 0.]]]
Build model...
Train...
Train on 6 samples
Epoch 1/200
6/6 [==============================] - 1s 147ms/sample - loss: 0.7373 - accuracy: 0.2917
Epoch 2/200
6/6 [==============================] - 0s 696us/sample - loss: 0.7211 - accuracy: 0.3750
Epoch 3/200
6/6 [==============================] - 0s 725us/sample - loss: 0.7054 - accuracy: 0.4167
Epoch 4/200
6/6 [==============================] - 0s 891us/sample - loss: 0.6903 - accuracy: 0.5000
Epoch 5/200
6/6 [==============================] - 0s 940us/sample - loss: 0.6758 - accuracy: 0.5833
Epoch 6/200
6/6 [==============================] - 0s 899us/sample - loss: 0.6618 - accuracy: 0.6250
Epoch 7/200
6/6 [==============================] - 0s 962us/sample - loss: 0.6484 - accuracy: 0.7083
Epoch 8/200
6/6 [==============================] - 0s 823us/sample - loss: 0.6355 - accuracy: 0.7500
Epoch 9/200
6/6 [========================

Epoch 74/200
6/6 [==============================] - 0s 849us/sample - loss: 0.3142 - accuracy: 0.8750
Epoch 75/200
6/6 [==============================] - 0s 797us/sample - loss: 0.3117 - accuracy: 0.8750
Epoch 76/200
6/6 [==============================] - 0s 744us/sample - loss: 0.3092 - accuracy: 0.8750
Epoch 77/200
6/6 [==============================] - 0s 902us/sample - loss: 0.3067 - accuracy: 0.8750
Epoch 78/200
6/6 [==============================] - 0s 824us/sample - loss: 0.3043 - accuracy: 0.8750
Epoch 79/200
6/6 [==============================] - 0s 671us/sample - loss: 0.3018 - accuracy: 0.8750
Epoch 80/200
6/6 [==============================] - 0s 660us/sample - loss: 0.2995 - accuracy: 0.8750
Epoch 81/200
6/6 [==============================] - 0s 704us/sample - loss: 0.2971 - accuracy: 0.8750
Epoch 82/200
6/6 [==============================] - 0s 813us/sample - loss: 0.2947 - accuracy: 0.8750
Epoch 83/200
6/6 [==============================] - 0s 708us/sample - loss: 0.2924

Epoch 154/200
6/6 [==============================] - 0s 870us/sample - loss: 0.1782 - accuracy: 0.9583
Epoch 155/200
6/6 [==============================] - 0s 705us/sample - loss: 0.1771 - accuracy: 0.9583
Epoch 156/200
6/6 [==============================] - 0s 676us/sample - loss: 0.1759 - accuracy: 0.9583
Epoch 157/200
6/6 [==============================] - 0s 779us/sample - loss: 0.1748 - accuracy: 0.9583
Epoch 158/200
6/6 [==============================] - 0s 815us/sample - loss: 0.1737 - accuracy: 0.9583
Epoch 159/200
6/6 [==============================] - 0s 735us/sample - loss: 0.1725 - accuracy: 0.9583
Epoch 160/200
6/6 [==============================] - 0s 657us/sample - loss: 0.1714 - accuracy: 0.9583
Epoch 161/200
6/6 [==============================] - 0s 655us/sample - loss: 0.1703 - accuracy: 0.9583
Epoch 162/200
6/6 [==============================] - 0s 741us/sample - loss: 0.1692 - accuracy: 0.9583
Epoch 163/200
6/6 [==============================] - 0s 689us/sample - lo

In [3]:
def runit(model, inp):
    inp = np.array(inp,dtype=np.float32)
    pred = model.predict(inp)
    return np.argmax(pred[0])

print( runit( model, [[[0],[1],[1],[0],[0],[0]]] ))


1


### Sun Spots Example - CNN

We now look at an example of CNN regression to predict sunspots.  You can find the data files needed for this example at the following location.

* [Sunspot Data Files](http://www.sidc.be/silso/datafiles#total)
* [Download Daily Sunspots](http://www.sidc.be/silso/INFO/sndtotcsv.php) - 1/1/1818 to now.

We use the following code to load the sunspot file:


In [4]:
import pandas as pd
import os

# Replacce the following path with your own file. It can be downloaded from:
# http://www.sidc.be/silso/INFO/sndtotcsv.php
path = "./data/"
    
filename = os.path.join(path,"SN_d_tot_V2.0.csv")    
names = ['year', 'month', 'day', 'dec_year', 'sn_value' , 
         'sn_error', 'obs_num']
df = pd.read_csv(filename,sep=';',header=None,names=names,
                 na_values=['-1'], index_col=False)

print("Starting file:")
print(df[0:10])

print("Ending file:")
print(df[-10:])

Starting file:
   year  month  day  dec_year  sn_value  sn_error  obs_num
0  1818      1    1  1818.001        -1       NaN        0
1  1818      1    2  1818.004        -1       NaN        0
2  1818      1    3  1818.007        -1       NaN        0
3  1818      1    4  1818.010        -1       NaN        0
4  1818      1    5  1818.012        -1       NaN        0
5  1818      1    6  1818.015        -1       NaN        0
6  1818      1    7  1818.018        -1       NaN        0
7  1818      1    8  1818.021        65      10.2        1
8  1818      1    9  1818.023        -1       NaN        0
9  1818      1   10  1818.026        -1       NaN        0
Ending file:
       year  month  day  dec_year  sn_value  sn_error  obs_num
73951  2020      6   21  2020.471         0       0.0       39
73952  2020      6   22  2020.474         0       0.0       43
73953  2020      6   23  2020.477         0       0.0       46
73954  2020      6   24  2020.480         0       0.0       42
73955  2

As you can see, there is quite a bit of missing data near the end of the file.  We want to find the starting index where the missing data no longer occurs.  This approach is somewhat sloppy; it would be better to find a use for the data between missing values.  However, the point of this example is to show how to use CNN with a somewhat simple time-series.

In [5]:
start_id = max(df[df['obs_num'] == 0].index.tolist())+1  # Find the last zero and move one beyond
print(start_id)
df = df[start_id:] # Trim the rows that have missing observations

11314


In [6]:
df['sn_value'] = df['sn_value'].astype(float)
df_train = df[df['year']<2000]
df_test = df[df['year']>=2000]

spots_train = df_train['sn_value'].tolist()
spots_test = df_test['sn_value'].tolist()

print("Training set has {} observations.".format(len(spots_train)))
print("Test set has {} observations.".format(len(spots_test)))

Training set has 55160 observations.
Test set has 7487 observations.


In [7]:
import numpy as np

def to_sequences(seq_size, obs):
    x = []
    y = []

    for i in range(len(obs)-SEQUENCE_SIZE-1):
        #print(i)
        window = obs[i:(i+SEQUENCE_SIZE)]
        after_window = obs[i+SEQUENCE_SIZE]
        window = [[x] for x in window]
        #print("{} - {}".format(window,after_window))
        x.append(window)
        y.append(after_window)
        
    return np.array(x),np.array(y)
    
    
SEQUENCE_SIZE = 25
x_train,y_train = to_sequences(SEQUENCE_SIZE,spots_train)
x_test,y_test = to_sequences(SEQUENCE_SIZE,spots_test)

print("Shape of training set: {}".format(x_train.shape))
print("Shape of test set: {}".format(x_test.shape))

Shape of training set: (55134, 25, 1)
Shape of test set: (7461, 25, 1)


In [8]:
x_train

array([[[353.],
        [240.],
        [275.],
        ...,
        [270.],
        [289.],
        [308.]],

       [[240.],
        [275.],
        [352.],
        ...,
        [289.],
        [308.],
        [327.]],

       [[275.],
        [352.],
        [268.],
        ...,
        [308.],
        [327.],
        [323.]],

       ...,

       [[ 97.],
        [ 79.],
        [ 70.],
        ...,
        [128.],
        [116.],
        [ 95.]],

       [[ 79.],
        [ 70.],
        [ 87.],
        ...,
        [116.],
        [ 95.],
        [ 85.]],

       [[ 70.],
        [ 87.],
        [ 81.],
        ...,
        [ 95.],
        [ 85.],
        [103.]]])

In [9]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, Dropout, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np

print('Build model...')
model = Sequential()
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', 
                 input_shape=(SEQUENCE_SIZE,1)))
model.add(Conv1D(filters=32, kernel_size=3, activation='relu'))
model.add(Dropout(0.2))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=50, 
                        verbose=1, mode='auto', restore_best_weights=True)
print('Train...')

model.fit(x_train,y_train,validation_data=(x_test,y_test),
          callbacks=[monitor],verbose=2,epochs=1000)

Build model...
Train...
Train on 55134 samples, validate on 7461 samples
Epoch 1/1000
55134/55134 - 14s - loss: 1040.9744 - val_loss: 490.5908
Epoch 2/1000
55134/55134 - 14s - loss: 936.3847 - val_loss: 651.4027
Epoch 3/1000
55134/55134 - 14s - loss: 916.2690 - val_loss: 626.4503
Epoch 4/1000
55134/55134 - 14s - loss: 900.3832 - val_loss: 571.8284
Epoch 5/1000
55134/55134 - 14s - loss: 893.3089 - val_loss: 413.6571
Epoch 6/1000
55134/55134 - 14s - loss: 895.3966 - val_loss: 629.9757
Epoch 7/1000
55134/55134 - 14s - loss: 889.4318 - val_loss: 539.9514
Epoch 8/1000
55134/55134 - 14s - loss: 880.3036 - val_loss: 674.7208
Epoch 9/1000
55134/55134 - 13s - loss: 877.0160 - val_loss: 673.2452
Epoch 10/1000
55134/55134 - 14s - loss: 870.8279 - val_loss: 549.1487
Epoch 11/1000
55134/55134 - 14s - loss: 872.3300 - val_loss: 517.0096
Epoch 12/1000
55134/55134 - 13s - loss: 869.3939 - val_loss: 576.2945
Epoch 13/1000
55134/55134 - 15s - loss: 863.1736 - val_loss: 675.4836
Epoch 14/1000
55134/55134

Finally, we evaluate the accuracy of the predictions.

In [10]:
from sklearn import metrics

# from sklearn import metrics
pred = model.predict(x_test)
score = np.sqrt(metrics.mean_squared_error(pred.flatten(),y_test))
print("Score (RMSE): {}".format(score))

Score (RMSE): 20.338562705967195
