# T81-558: Applications of Deep Neural Networks
**Class 2: Introduction to TensorFlow.**
* Instructor: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), School of Engineering and Applied Science, [Washington University in St. Louis](https://engineering.wustl.edu/Programs/Pages/default.aspx)
* For more information visit the [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

## Neural Network Basics

Neural networks were one of the first machine learning models.  Their popularity has fallen twice and is now on its third rise.  Deep learning implies the use of neural networks.  The "deep" in deep learning refers to a neural network with many hidden layers.  Because neural networks have been around for so long, they have quite a bit of baggage.  Many different training algorithms, activation/transfer functions, and structures have been added over the years.  This course is only concerned with the latest, most current state of the art techniques for deep neural networks.  I am not going to spend any time discussing the history of neural networks.  If you would like to learn about some of the more classic structures of neural networks, there are several chapters dedicated to this in your course book.  For the latest technology, I wrote an article for the Society of Actuaries on deep learning as the [third generation of neural networks](https://www.soa.org/Library/Newsletters/Predictive-Analytics-and-Futurism/2015/december/paf-iss12.pdf).

Neural networks accept input and produce output.  The input to a neural network is called the feature vector.  The size of this vector is always a fixed size.  Changing the size of the feature vector means recreating the entire neural network.  Though the feature vector is called a "vector," this is not always the case.  A vector implies a 1D array.  Historically the input to a neural network was always 1D.  However, with modern neurals network you might see inputs, such as:

* **1D Vector** - Class input to a neural network, similar to rows in a spreadsheet.  Common in predictive modeling.
* **2D Matrix** - Grayscale image input to a convolutional neural network (CNN).
* **3D Matrix** - Color image input to a convolutional neural network (CNN).
* **nD Matrix** - Higher order input to a CNN.

Prior to CNN's, the image input was sent to a neural network simply by squashing the image matrix into a long array by placing the images rows side-by-side.  CNN's are different, as the nD matrix literally passes through the neural network layers.

Initially this course will focus upon 1D input to neural networks.  However, later sessions will focus more heavily upon higher dimension input.

**Dimensions** The term dimension can be confusing in neural networks.  In the sense of a 1D input vector, dimension refers to how many elements are in that 1D array.  For example a neural network with 10 input neurons has 10 dimensions.  However, now that we have CNN's, the input has dimensions too.  The input to the neural network will *usually* have 1, 2 or 3 dimensions.  4 or more dimensions is unusual.  You might have a 2D input to a neural network that has 64x64 pixels.  This would result in 4,096 input neurons.  This network is either 2D or 4,096D, depending on which set of dimensions you are talking about!

# Classification or Regression

Like many models, neural networks can function in classification or regression:

* **Regression** - You expect a number as your neural network's prediction.
* **Classification** - You expect a class/category as your neural network's prediction.

The following shows a classification and regression neural network:

![Neural Network Classification and Regression](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_ann_class_reg.png "Neural Network Classification and Regression")

Notice that the output of the regression neural network is numeric and the output of the classification is a class.  Regression, or two-class classification, networks always have a single output.  Classification neural networks have an output neuron for each class. 

The following diagram shows a typical neural network:

![Feedforward Neural Networks](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_ann.png "Feedforward Neural Networks")

There are usually four types of neurons in a neural network:

* **Input Neurons** - Each input neuron is mapped to one element in the feature vector.
* **Hidden Neurons** - Hidden neurons allow the neural network to abstract and process the input into the output.
* **Output Neurons** - Each output neuron calculates one part of the output.
* **Context Neurons** - Holds state between calls to the neural network to predict.
* **Bias Neurons** - Work similar to the y-intercept of a linear equation.  

These neurons are grouped into layers:

* **Input Layer** - The input layer accepts feature vectors from the dataset.  Input layers usually have a bias neuron.
* **Output Layer** - The output from the neural network.  The output layer does not have a bias neuron.
* **Hidden Layers** - Layers that occur between the input and output layers.  Each hidden layer will usually have a bias neuron.



# Neuron Calculation

The output from a single neuron is calculated according to the following formula:

$ f(x,w) = \theta(\sum_i(w_i \cdot x_i)) $

The input vector (x) represents the feature vector.  To account for the bias neuron, a value of 1 is always appended to the end of the input feature vector.  This causes the last weight to be interpreted as a bias value that is simply added to the summation. 

Consider using the above equation to calculate the output from the following neuron:

![Single Neuron](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_abstract_nn.png "Single Neuron")

The above neuron has 2 inputs plus the bias as a third.  This neuron might accept the following input feature vector:

```
[1,2]
```

To account for the bias neuron, a 1 is appended, as follows:

```
[1,2,1]
```

The weights for a 3-input layer (2 real inputs + bias) will always have an additional weight, for the bias.  A weight vector might be:

```
[ 0.1, 0.2, 0.3]
```

To calculate the summation, perform the following:

```
0.1*1 + 0.2*2 + 0.3*3 = 1.4
```

The value of 1.4 is passed to the $\theta$ function, which represents the activation function.



# Activation Functions

Activation functions, also known as transfer functions, are used to calculate the output of each layer of a neural network.  Historically neural networks have used a hyperbolic tangent, sigmoid/logistic, or linear activation function.  However, modern deep neural networks primarily make use of the following activation functions:

* **Rectified Linear Unit (ReLU)** - Used for the output of hidden layers.
* **Softmax** - Used for the output of classification neural networks.
* **Linear** - Used for the output of regression neural networks (or 2-class classification).

The ReLU function is calculated as follows:

$ \theta(x) = \max(0, x) $

The Softmax is calculated as follows:

$ \theta_i(z) = \frac{e^{z_i}}{\sum\limits_{j \in group}e^{z_j}} $

The Softmax activation function is only useful with more than one output neuron.  It ensures that all of the output neurons sum to 1.0.  This makes it very useful for classification where it shows the probability of each of the classes as being the correct choice.

To experiment with the Softmax, click [here](http://www.heatonresearch.com/aifh/vol3/softmax.html).

The linear activation function is essentially no activation function:

$ \theta(x) = x $

For regression problems, this is the activation function of choice.  



# Why ReLU?

Why is the ReLU activation function so popular?  It was one of the key improvements to neural networks that makes deep learning work. Prior to deep learning, the sigmoid activation function was very common:

$ \theta(x) = \frac{1}{1 + e^{-x}} $

The graph of the sigmoid function is shown here:

![Sigmoid Activation Function](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_sigmoid.png "Sigmoid Activation Function")

Neural networks are often trained using gradient descent.  To make use of gradient descent, it is necessary to take the derivative of the activation function.  This allows the partial derivatives of each of the weights to be calculated with respect to the error function.  A derivative is the instantaneous rate of change:

![Derivative](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_deriv.png "Derivative")

The derivative of the sigmoid function is given here:

$ \theta'(x)=\theta(x)(1-\theta(x)) $

This derivative is often given in other forms.  The above form is used for computational efficiency. To see how this derivative was taken, see [this](http://www.heatonresearch.com/aifh/vol3/deriv_sigmoid.html).

The graph of the sigmoid derivative is given here:

![Sigmoid Derivative](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_deriv_sigmoid.png "Sigmoid Derivative")

The derivative quickly saturates to zero as *x* moves from zero.  This is not a problem for the derivative of the ReLU, which is given here:

$ \theta'(x) = \begin{cases} 1 & x > 0 \\ 0 & x \leq 0 \end{cases} $

# Why are Bias Neurons Needed?

The activation functions seen in the previous section specify the output of a single neuron.  Together, the weight and bias of a neuron shape the output of the activation to produce the desired output.  To see how this process occurs, consider the following equation. It represents a single-input sigmoid activation neural network.

$ f(x,w,b) = \frac{1}{1 + e^{-(wx+b)}} $ 

The *x* variable represents the single input to the neural network.  The *w* and *b* variables specify the weight and bias of the neural network.  The above equation is a combination of the weighted sum of the inputs and the sigmoid activation function.  For this section, we will consider the sigmoid function because it clearly demonstrates the effect that a bias neuron has.

The weights of the neuron allow you to adjust the slope or shape of the activation function.  The following figure shows the effect on the output of the sigmoid activation function if the weight is varied:

![Adjusting Weight](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_bias_weight.png "Bias 1")

The above diagram shows several sigmoid curves using the following parameters:

```
f(x,0.5,0.0)
f(x,1.0,0.0)
f(x,1.5,0.0)
f(x,2.0,0.0)
```

To produce the curves, we did not use bias, which is evident in the third parameter of 0 in each case. Using four weight values yields four different sigmoid curves in the above figure. No matter the weight, we always get the same value of 0.5 when x is 0 because all of the curves hit the same point when x is 0.  We might need the neural network to produce other values when the input is near 0.5.  

Bias does shift the sigmoid curve, which allows values other than 0.5 when x is near 0. The following figure shows the effect of using a weight of 1.0 with several different biases:


![Adjusting Bias](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_bias_value.png "Bias 1")

The above diagram shows several sigmoid curves with the following parameters:

```
f(x,1.0,1.0)
f(x,1.0,0.5)
f(x,1.0,1.5)
f(x,1.0,2.0)
```

We used a weight of 1.0 for these curves in all cases.  When we utilized several different biases, sigmoid curves shifted to the left or right.  Because all the curves merge together at the top right or bottom left, it is not a complete shift.

When we put bias and weights together, they produced a curve that created the necessary output from a neuron.  The above curves are the output from only one neuron.  In a complete network, the output from many different neurons will combine to produce complex output patterns.

# TensorFlow - Google

![TensorFlow](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_tensorflow.png "TensorFlow")

https://www.tensorflow.org/

# What version of TensorFlow do you have?

In [1]:
import tensorflow as tf
print("Tensor Flow Version: {}".format(tf.__version__))

Tensor Flow Version: 0.8.0


# Installing TensorFlow

* [IBM Data Scientist Workbench](datascientistworkbench.com) - All platforms, use your browser.
* Windows - Installing TensorFlow on Windows is not easy. Docker is your best option. [Hopefully this will improve in the future](https://github.com/tensorflow/tensorflow/issues/17).
* Mac - Supported platform.
* Linux - Supported platform.

[TensorFlow Setup Instructions](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#docker-based_installation)

# Why TensorFlow

* Supported by Google
* Works well on Linux/Mac
* Excellent GPU support
* Python is an easy to learn programming language
* Python is [extremely popular](http://www.kdnuggets.com/2014/08/four-main-languages-analytics-data-mining-data-science.html) in the data science community

# Other Deep Learning Tools
TensorFlow is not the only only game in town.  These are some of the best supported alternatives.  Most of these are written in C++. In order of my own preference (I have used all of these):

* [Theano](http://deeplearning.net/software/theano/) - Python, from the academics that created deep learning.  GPU support.
* [Computational Network Toolkit (CNTK)](https://github.com/Microsoft/CNTK) - Microsoft.  Support for Windows/Linux, command line only.  Bindings for predictions for C#/Python. GPU support.
* [Caffe](http://caffe.berkeleyvision.org/) Academic project from Berkeley.  Python.  
* [H2O](http://www.h2o.ai/) - Java based.  Supports all major platforms.  Limited support for computer vision. No GPU support.
* [Deeplearning4J](http://deeplearning4j.org/) - Java based. Supports all major platforms. GPU support in Java!

# Extreme Deep Learning

[Torch](http://torch.ch/) is used by Google DeepMind, the Facebook AI Research Group, IBM, Yandex and the Idiap Research Institute.  It has been used for some of the most advanced deep learning projects in the world.  However, it requires the [LUA](https://en.wikipedia.org/wiki/Lua_(programming_language)) programming language.  It is very advanced, but it is not mainstream.  I have not worked with Torch (yet!).

# Using TensorFlow

TensorFlow is a low-level mathematics API, similar to [Numpy](http://www.numpy.org/).  However, unlike Numpy, TensorFlow is built for deep learning.  TensorFlow works by allowing you to define compute graphs with Python.  In this regard, it is similar to [Spark](http://spark.apache.org/).  TensorFlow compiles these compute graphs into highly efficient C++/[CUDA](https://en.wikipedia.org/wiki/CUDA) code.

The [TensorBoard](https://www.tensorflow.org/versions/r0.10/how_tos/summaries_and_tensorboard/index.html) command line utility can be used to view these graphs.  The iris neural network's graph used in this class is shown here:

![Iris Graph](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_graph_tf.png "Iris Graph")

Expanding the DNN gives:


![Iris DNN Graph](https://raw.githubusercontent.com/jeffheaton/t81_558_deep_learning/master/images/class_2_graph_dnn.png "Iris DNN Graph")


# Using Skflow

Skflow is layer on top of Tensorflow that makes it much easier to create neural networks.  Rather than define the graphs, like you see above, you define the individual layers of the network with a much more high level API.  Unless you are performing research into entirely new structures of deep neural networks it is unlikely that you need to program TensorFlow directly.  

**For this class, we will use SKFLOW, rather than direct TensorFlow**

SKFLOW is built into TensorFlow, as of v0.8.  This makes it very easy to use.

All examples in this class will use SKFLOW, and you are encouraged to use it for the programming assignments.

# Simple TensorFlow Classification: Iris

This is a very simple example of how to perform the Iris classification using TensorFlow.  The iris.csv file is used, rather than using the built-in files that many of the Google examples require.  

In [2]:
import tensorflow.contrib.learn as skflow
from sklearn import metrics
import pandas as pd
import os
from sklearn import preprocessing

path = "./data/"

# Read iris dataset
filename_read = os.path.join(path,"iris.csv")
df = pd.read_csv(filename_read,na_values=['NA','?'])

# Extract just the columns we shall predict on
trainDF = df[['sepal_l','sepal_w','petal_l','petal_w']]

# Create the x-side (feature vectors) of the training
x = trainDF.as_matrix()

# Create the y-side (targets) of the training
le = preprocessing.LabelEncoder()
y = le.fit_transform(df['species'])

# Create a deep neural network with 3 hidden layers of 10, 20, 10
classifier = skflow.TensorFlowDNNClassifier(hidden_units=[10, 20, 10], n_classes=3,steps=200)

# Fit/train neural network
classifier.fit(x, y)

# Measure accuracy
score = metrics.accuracy_score(y, classifier.predict(x))
print("Final score: {}".format(score))

# How to make many predictions
pred = classifier.predict(x)
predDF = pd.DataFrame(pred)
pred_nameDF = pd.DataFrame(le.classes_[pred])
df2 = pd.concat([trainDF,predDF,pred_nameDF,df['species']],axis=1)
df2.columns = ['sepal_l','sepal_w','petal_l','petal_w','pred','pred_str','ideal']
df2

Step #100, epoch #20, avg. train loss: 0.55053
Step #200, epoch #40, avg. train loss: 0.15876
Final score: 0.9466666666666667


sepal_l  sepal_w  petal_l  petal_w  pred         pred_str           ideal
0        5.1      3.5      1.4      0.2     0      Iris-setosa     Iris-setosa
1        4.9      3.0      1.4      0.2     0      Iris-setosa     Iris-setosa
2        4.7      3.2      1.3      0.2     0      Iris-setosa     Iris-setosa
3        4.6      3.1      1.5      0.2     0      Iris-setosa     Iris-setosa
4        5.0      3.6      1.4      0.2     0      Iris-setosa     Iris-setosa
5        5.4      3.9      1.7      0.4     0      Iris-setosa     Iris-setosa
6        4.6      3.4      1.4      0.3     0      Iris-setosa     Iris-setosa
7        5.0      3.4      1.5      0.2     0      Iris-setosa     Iris-setosa
8        4.4      2.9      1.4      0.2     0      Iris-setosa     Iris-setosa
9        4.9      3.1      1.5      0.1     0      Iris-setosa     Iris-setosa
10       5.4      3.7      1.5      0.2     0      Iris-setosa     Iris-setosa
11       4.8      3.4      1.6      0.2     0      Iris-setosa     Iris-setosa
12       4.8      3.0      1.4      0.1     0      Iris-setosa     Iris-setosa
13       4.3      3.0      1.1      0.1     0      Iris-setosa     Iris-setosa
14       5.8      4.0      1.2      0.2     0      Iris-setosa     Iris-setosa
15       5.7      4.4      1.5      0.4     0      Iris-setosa     Iris-setosa
16       5.4      3.9      1.3      0.4     0      Iris-setosa     Iris-setosa
17       5.1      3.5      1.4      0.3     0      Iris-setosa     Iris-setosa
18       5.7      3.8      1.7      0.3     0      Iris-setosa     Iris-setosa
19       5.1      3.8      1.5      0.3     0      Iris-setosa     Iris-setosa
20       5.4      3.4      1.7      0.2     0      Iris-setosa     Iris-setosa
21       5.1      3.7      1.5      0.4     0      Iris-setosa     Iris-setosa
22       4.6      3.6      1.0      0.2     0      Iris-setosa     Iris-setosa
23       5.1      3.3      1.7      0.5     0      Iris-setosa     Iris-setosa
24       4.8      3.4      1.9      0.2     0      Iris-setosa     Iris-setosa
25       5.0      3.0      1.6      0.2     0      Iris-setosa     Iris-setosa
26       5.0      3.4      1.6      0.4     0      Iris-setosa     Iris-setosa
27       5.2      3.5      1.5      0.2     0      Iris-setosa     Iris-setosa
28       5.2      3.4      1.4      0.2     0      Iris-setosa     Iris-setosa
29       4.7      3.2      1.6      0.2     0      Iris-setosa     Iris-setosa
..       ...      ...      ...      ...   ...              ...             ...
120      6.9      3.2      5.7      2.3     2   Iris-virginica  Iris-virginica
121      5.6      2.8      4.9      2.0     2   Iris-virginica  Iris-virginica
122      7.7      2.8      6.7      2.0     2   Iris-virginica  Iris-virginica
123      6.3      2.7      4.9      1.8     2   Iris-virginica  Iris-virginica
124      6.7      3.3      5.7      2.1     2   Iris-virginica  Iris-virginica
125      7.2      3.2      6.0      1.8     2   Iris-virginica  Iris-virginica
126      6.2      2.8      4.8      1.8     1  Iris-versicolor  Iris-virginica
127      6.1      3.0      4.9      1.8     1  Iris-versicolor  Iris-virginica
128      6.4      2.8      5.6      2.1     2   Iris-virginica  Iris-virginica
129      7.2      3.0      5.8      1.6     1  Iris-versicolor  Iris-virginica
130      7.4      2.8      6.1      1.9     2   Iris-virginica  Iris-virginica
131      7.9      3.8      6.4      2.0     1  Iris-versicolor  Iris-virginica
132      6.4      2.8      5.6      2.2     2   Iris-virginica  Iris-virginica
133      6.3      2.8      5.1      1.5     1  Iris-versicolor  Iris-virginica
134      6.1      2.6      5.6      1.4     2   Iris-virginica  Iris-virginica
135      7.7      3.0      6.1      2.3     2   Iris-virginica  Iris-virginica
136      6.3      3.4      5.6      2.4     2   Iris-virginica  Iris-virginica
137      6.4      3.1      5.5      1.8     2   Iris-virginica  Iris-virginica
138      6.0      3.0      4.8      1.8     1  Iris-ver

In [5]:
import numpy as np
# How to make predictions one at a time, in a loop
for fv in x:
    # Flip the feature vector to the right shape
    fv2 = fv.reshape((1,4))
    #  Compute a prediction for the 3 classes, this will return 0, 1 or 2.
    pred = classifier.predict(fv2)
    # Turn the numeric prediction to a text string (e.g. Iris-virginica)
    pred_name = le.classes_[pred][0]
    # Output result
    print("{} : {} ({})".format(fv,pred,pred_name))

[ 5.1  3.5  1.4  0.2] : [0] (Iris-setosa)
[ 4.9  3.   1.4  0.2] : [0] (Iris-setosa)
[ 4.7  3.2  1.3  0.2] : [0] (Iris-setosa)
[ 4.6  3.1  1.5  0.2] : [0] (Iris-setosa)
[ 5.   3.6  1.4  0.2] : [0] (Iris-setosa)
[ 5.4  3.9  1.7  0.4] : [0] (Iris-setosa)
[ 4.6  3.4  1.4  0.3] : [0] (Iris-setosa)
[ 5.   3.4  1.5  0.2] : [0] (Iris-setosa)
[ 4.4  2.9  1.4  0.2] : [0] (Iris-setosa)
[ 4.9  3.1  1.5  0.1] : [0] (Iris-setosa)
[ 5.4  3.7  1.5  0.2] : [0] (Iris-setosa)
[ 4.8  3.4  1.6  0.2] : [0] (Iris-setosa)
[ 4.8  3.   1.4  0.1] : [0] (Iris-setosa)
[ 4.3  3.   1.1  0.1] : [0] (Iris-setosa)
[ 5.8  4.   1.2  0.2] : [0] (Iris-setosa)
[ 5.7  4.4  1.5  0.4] : [0] (Iris-setosa)
[ 5.4  3.9  1.3  0.4] : [0] (Iris-setosa)
[ 5.1  3.5  1.4  0.3] : [0] (Iris-setosa)
[ 5.7  3.8  1.7  0.3] : [0] (Iris-setosa)
[ 5.1  3.8  1.5  0.3] : [0] (Iris-setosa)
[ 5.4  3.4  1.7  0.2] : [0] (Iris-setosa)
[ 5.1  3.7  1.5  0.4] : [0] (Iris-setosa)
[ 4.6  3.6  1.   0.2] : [0] (Iris-setosa)
[ 5.1  3.3  1.7  0.5] : [0] (Iris-

In [6]:
# ad hoc prediction
sample_flower = np.ndarray(buffer=np.array([5.0,3.0,4.0,2.0]),shape=(1,4))
pred = classifier.predict(sample_flower)
print("Predict that {} is: {}".format(sample_flower,le.classes_[pred]))

Predict that [[ 5.  3.  4.  2.]] is: ['Iris-virginica']


# Simple TensorFlow Regression: MPG

This example shows how to encode the MPG dataset for regression.  This is slightly more complex than Iris, because:

* Input has both numeric and categorical
* Input has missing values

To encode categorical values that are part of the feature vector, you can use the handy function I provide below.  If the categorical value is the target (as was the case with Iris, use the same technique as Iris). The iris technique allows you to decode back to Iris text strings from the predictions.

In [7]:
# Handy function to encode catagoricals
def encode_categorical(trainDF,name,df):
    one_hot = pd.get_dummies(df[name])
    one_hot.columns = ["{}-{}".format(name,x) for x in one_hot.columns]
    return trainDF.join(one_hot)

In [8]:
import tensorflow.contrib.learn as skflow
import pandas as pd
import os
import numpy as np
from sklearn import metrics
from scipy.stats import zscore

path = "./data/"

# Handy function to encode catagoricals
def encode_categorical(trainDF,name,df):
    one_hot = pd.get_dummies(df[name])
    one_hot.columns = ["{}-{}".format(name,x) for x in one_hot.columns]
    return trainDF.join(one_hot)

filename_read = os.path.join(path,"auto-mpg.csv")
df = pd.read_csv(filename_read)
df = pd.read_csv(filename_read,na_values=['NA','?'])

# Create training dataset - numerics as zscore
trainDF = df[['horsepower','weight','cylinders','displacement','acceleration','origin']].copy()

# Handle missing values in horsepower
med = trainDF['horsepower'].median()
trainDF['horsepower'] = trainDF['horsepower'].fillna(med)

# Convert to zscores
trainDF['horsepower'] = zscore(trainDF['horsepower'])
trainDF['weight'] = zscore(trainDF['weight'])
trainDF['cylinders'] = zscore(trainDF['cylinders'])
trainDF['displacement'] = zscore(trainDF['displacement'])
trainDF['acceleration'] = zscore(trainDF['acceleration'])
trainDF = encode_categorical(trainDF,'origin',df)

# Display training data
trainDF

# Encode to a 2D matrix for training
x = trainDF.as_matrix()
y = df['mpg']

# Create a deep neural network with 3 hidden layers of 50, 25, 10
regressor = skflow.TensorFlowDNNRegressor(hidden_units=[50, 25, 10], steps=5000)

# Fit/train neural network
regressor.fit(x, y)

# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(regressor.predict(x),y))
print("Final score (RMSE): {}".format(score))

# How to make many predictions
pred = regressor.predict(x)
predDF = pd.DataFrame(pred)
df2 = pd.concat([df,predDF,pd.DataFrame(y)],axis=1)

df2.columns = list(df.columns)+['pred','ideal']
df2

Step #100, epoch #7, avg. train loss: 19.83904
Step #200, epoch #15, avg. train loss: 8.88547
Step #300, epoch #23, avg. train loss: 7.34669
Step #400, epoch #30, avg. train loss: 7.14665
Step #500, epoch #38, avg. train loss: 7.04568
Step #600, epoch #46, avg. train loss: 6.55011
Step #700, epoch #53, avg. train loss: 6.64211
Step #800, epoch #61, avg. train loss: 6.35688
Step #900, epoch #69, avg. train loss: 6.32442
Step #1000, epoch #76, avg. train loss: 6.10804
Step #1100, epoch #84, avg. train loss: 5.99199
Step #1200, epoch #92, avg. train loss: 5.88154
Step #1300, epoch #100, avg. train loss: 5.86253
Step #1400, epoch #107, avg. train loss: 5.71351
Step #1500, epoch #115, avg. train loss: 5.43558
Step #1600, epoch #123, avg. train loss: 5.72406
Step #1700, epoch #130, avg. train loss: 5.50822
Step #1800, epoch #138, avg. train loss: 5.37541
Step #1900, epoch #146, avg. train loss: 5.43317
Step #2000, epoch #153, avg. train loss: 5.29254
Step #2100, epoch #161, avg. train loss: 

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0    18.0          8         307.0       130.0    3504          12.0    70   
1    15.0          8         350.0       165.0    3693          11.5    70   
2    18.0          8         318.0       150.0    3436          11.0    70   
3    16.0          8         304.0       150.0    3433          12.0    70   
4    17.0          8         302.0       140.0    3449          10.5    70   
5    15.0          8         429.0       198.0    4341          10.0    70   
6    14.0          8         454.0       220.0    4354           9.0    70   
7    14.0          8         440.0       215.0    4312           8.5    70   
8    14.0          8         455.0       225.0    4425          10.0    70   
9    15.0          8         390.0       190.0    3850           8.5    70   
10   15.0          8         383.0       170.0    3563          10.0    70   
11   14.0          8         340.0       160.0    3609           8.0    70   
12   15.0          8         400.0       150.0    3761           9.5    70   
13   14.0          8         455.0       225.0    3086          10.0    70   
14   24.0          4         113.0        95.0    2372          15.0    70   
15   22.0          6         198.0        95.0    2833          15.5    70   
16   18.0          6         199.0        97.0    2774          15.5    70   
17   21.0          6         200.0        85.0    2587          16.0    70   
18   27.0          4          97.0        88.0    2130          14.5    70   
19   26.0          4          97.0        46.0    1835          20.5    70   
20   25.0          4         110.0        87.0    2672          17.5    70   
21   24.0          4         107.0        90.0    2430          14.5    70   
22   25.0          4         104.0        95.0    2375          17.5    70   
23   26.0          4         121.0       113.0    2234          12.5    70   
24   21.0          6         199.0        90.0    2648          15.0    70   
25   10.0          8         360.0       215.0    4615          14.0    70   
26   10.0          8         307.0       200.0    4376          15.0    70   
27   11.0          8         318.0       210.0    4382          13.5    70   
28    9.0          8         304.0       193.0    4732          18.5    70   
29   27.0          4          97.0        88.0    2130          14.5    71   
..    ...        ...           ...         ...     ...           ...   ...   
368  27.0          4         112.0        88.0    2640          18.6    82   
369  34.0          4         112.0        88.0    2395          18.0    82   
370  31.0          4         112.0        85.0    2575          16.2    82   
371  29.0          4         135.0        84.0    2525          16.0    82   
372  27.0          4         151.0        90.0    2735          18.0    82   
373  24.0          4         140.0        92.0    2865          16.4    82   
374  23.0          4         151.0         NaN    3035          20.5    82   
375  36.0          4         105.0        74.0    1980          15.3    82   
376  37.0          4          91.0        68.0    2025          18.2    82   
377  31.0          4          91.0        68.0    1970          17.6    82   
378  38.0          4         105.0        63.0    2125          14.7    82   
379  36.0          4          98.0        70.0    2125          17.3    82   
380  36.0          4         120.0        88.0    2160          14.5    82   
381  36.0          4         107.0        75.0    2205          14.5    82   
382  34.0          4         108.0        70.0    2245          16.9    82   
383  38.0          4          91.0        67.0    1965          15.0    82   
384  32.0          4          91.0        67.0    1965          15.7    82   
385  38.0          4          91.0        67.0    1995          16.2    82   
386  25.0          6         181.0       110.0    2945          16.4    82   
387  38.0          6        

# Load/Save Trained Network

The code below saves a TensorFlow network to a directory.  This directory can be used to reload your weights, without retraining.  Because training can take a **long** time, this is critical.

The following code trains an Iris dataset, reports the error, saves/reloads it, and reports the same error.

In [9]:
import tensorflow.contrib.learn as skflow
from sklearn import metrics
import pandas as pd
import os
from sklearn import preprocessing

path = "./data/"

# Read iris dataset
filename_read = os.path.join(path,"iris.csv")
df = pd.read_csv(filename_read,na_values=['NA','?'])

# Extract just the columns we shall predict on
trainDF = df[['sepal_l','sepal_w','petal_l','petal_w']]

# Create the x-side (feature vectors) of the training
x = trainDF.as_matrix()

# Create the y-side (targets) of the training
le = preprocessing.LabelEncoder()
y = le.fit_transform(df['species'])

# Create a deep neural network with 3 hidden layers of 10, 20, 10
classifier = skflow.TensorFlowDNNClassifier(hidden_units=[10, 20, 10], n_classes=3,steps=200)

# Fit/train neural network
classifier.fit(x, y)

# Measure accuracy
score = metrics.accuracy_score(y, classifier.predict(x))
print("Final score: {}".format(score))

# Save the neural network to a directory
classifier.save("./iris-network")
classifier = None # Kill it

# Reload it
classifier2 = skflow.TensorFlowEstimator.restore("./iris-network")

# Prove that the reloaded is the same as the original
score = metrics.accuracy_score(y, classifier2.predict(x))
print("Saved final score: {}".format(score))

Step #100, epoch #20, avg. train loss: 0.55053
Step #200, epoch #40, avg. train loss: 0.15876
Final score: 0.9466666666666667
Saved final score: 0.9466666666666667


# View Graph for Neural Network

TensorFlow includes the command line utility called [**tensorboard**](https://www.tensorflow.org/versions/r0.10/how_tos/summaries_and_tensorboard/index.html) that can be used to visualize the neural networks.  It is not needed for this course, but it can be handy to see your neural network, and I will use it in lecture a few times.  It does not work with IBM Data Scientist Workbench, so you will need a native install if you would like to use it.

To make use of it, you must specify a **logdir** on the fit command, for example:

```
classifier.fit(x, y, logdir='./log/')
```

Once the **fit** occurs, the logdir will be filled with files that **tensorboard** will use.  To view the graph, issue the following command:

```
tensorboard --logdir ./log
```

