<a href="https://colab.research.google.com/github/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_10_5_temporal_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# T81-558: Applications of Deep Neural Networks
**Module 10: Time Series in Keras**
* Instructor: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), McKelvey School of Engineering, [Washington University in St. Louis](https://engineering.wustl.edu/Programs/Pages/default.aspx)
* For more information visit the [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

# Module 10 Material

* Part 10.1: Time Series Data Encoding for Deep Learning [[Video]](https://www.youtube.com/watch?v=dMUmHsktl04&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_1_timeseries.ipynb)
* Part 10.2: Programming LSTM with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=wY0dyFgNCgY&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_2_lstm.ipynb)
* Part 10.3: Text Generation with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=6ORnRAz3gnA&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_3_text_generation.ipynb)
* Part 10.4: Image Captioning with Keras and TensorFlow [[Video]](https://www.youtube.com/watch?v=NmoW_AYWkb4&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_4_captioning.ipynb)
* **Part 10.5: Temporal CNN in Keras and TensorFlow** [[Video]](https://www.youtube.com/watch?v=i390g8acZwk&list=PLjy4p-07OYzulelvJ5KVaT2pDlxivl_BN) [[Notebook]](t81_558_class_10_5_temporal_cnn.ipynb)

# Google CoLab Instructions

The following code ensures that Google CoLab is running the correct version of TensorFlow.
  Running the following code will map your GDrive to ```/content/drive```.

In [1]:
try:
    %tensorflow_version 2.x
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Note: not using Google CoLab


# Part 10.5: Temporal CNN in Keras and TensorFlow

Traditionally, we use Convolutional Neural Networks (CNNs) for image classification problems and Long Short Term Memory (LSTM) networks for time series.  However, recent research has shown CNN's to be beneficial at time series problems. We begin similarly to how we started for LSTM by attempting to classify simple numeric sequences.  The data preparation is nearly identical to LSTM; however, the neural network consists of a **Conv1D** layer this time around.  The following code prepares the data and constructs the neural network.

In [2]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D
import numpy as np

max_features = 4 # 0,1,2,3 (total of 4)
x = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[2],[2],[0]],
    [[0],[0],[0],[0],[3],[3]],
    [[0],[2],[2],[0],[0],[0]],
    [[0],[0],[3],[3],[0],[0]],
    [[0],[0],[0],[0],[1],[1]]
]
x = np.array(x,dtype=np.float32)
y = np.array([1,2,3,2,3,1],dtype=np.int32)

# Convert y2 to dummy variables
y2 = np.zeros((y.shape[0], max_features),dtype=np.float32)
y2[np.arange(y.shape[0]), y] = 1.0
y2 = np.asarray(y2).astype('float32').reshape((-1,1,4))
print(y2)

print('Build model...')
model = Sequential()
model.add(Conv1D(128, kernel_size=x.shape[1], input_shape=(None, 1)))
model.add(Dense(4, activation='sigmoid'))

# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print('Train...')
model.fit(x,y2,epochs=200)
pred = model.predict(x)
predict_classes = np.argmax(pred,axis=1)
print("Predicted classes: {}",predict_classes)
print("Expected classes: {}",predict_classes)

Init Plugin
Init Graph Optimizer
Init Kernel
[[[0. 1. 0. 0.]]

 [[0. 0. 1. 0.]]

 [[0. 0. 0. 1.]]

 [[0. 0. 1. 0.]]

 [[0. 0. 0. 1.]]

 [[0. 1. 0. 0.]]]
Build model...
Metal device set to: Apple M1
Train...
Epoch 1/200
1/1 [==============================] - 0s 189ms/step - loss: 0.6984 - accuracy: 0.1667
Epoch 2/200
1/1 [==============================] - 0s 7ms/step - loss: 0.6838 - accuracy: 0.1667
Epoch 3/200
1/1 [==============================] - 0s 9ms/step - loss: 0.6697 - accuracy: 0.3333
Epoch 4/200
1/1 [==============================] - 0s 8ms/step - loss: 0.6561 - accuracy: 0.3333
Epoch 5/200
1/1 [==============================] - 0s 8ms/step - loss: 0.6431 - accuracy: 0.3333
Epoch 6/200
1/1 [==============================] - 0s 11ms/step - loss: 0.6305 - accuracy: 0.5000
Epoch 7/200
1/1 [==============================] - 0s 8ms/step - loss: 0.6185 - accuracy: 0.5000
Epoch 8/200
1/1 [==============================] - 0s 11ms/step - loss: 0.6069 - accuracy: 0.5000
Epoch 9/200
1

1/1 [==============================] - 0s 8ms/step - loss: 0.2792 - accuracy: 0.6667
Epoch 83/200
1/1 [==============================] - 0s 7ms/step - loss: 0.2768 - accuracy: 0.6667
Epoch 84/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2745 - accuracy: 0.6667
Epoch 85/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2722 - accuracy: 0.6667
Epoch 86/200
1/1 [==============================] - 0s 7ms/step - loss: 0.2699 - accuracy: 0.6667
Epoch 87/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2677 - accuracy: 0.6667
Epoch 88/200
1/1 [==============================] - 0s 7ms/step - loss: 0.2654 - accuracy: 0.6667
Epoch 89/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2632 - accuracy: 0.6667
Epoch 90/200
1/1 [==============================] - 0s 7ms/step - loss: 0.2610 - accuracy: 0.8333
Epoch 91/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2589 - accuracy: 0.8333
Epoch 92/200
1/1 [===============

1/1 [==============================] - 0s 8ms/step - loss: 0.1479 - accuracy: 1.0000
Epoch 166/200
1/1 [==============================] - 0s 7ms/step - loss: 0.1467 - accuracy: 1.0000
Epoch 167/200
1/1 [==============================] - 0s 8ms/step - loss: 0.1456 - accuracy: 1.0000
Epoch 168/200
1/1 [==============================] - 0s 7ms/step - loss: 0.1445 - accuracy: 1.0000
Epoch 169/200
1/1 [==============================] - 0s 8ms/step - loss: 0.1434 - accuracy: 1.0000
Epoch 170/200
1/1 [==============================] - 0s 7ms/step - loss: 0.1423 - accuracy: 1.0000
Epoch 171/200
1/1 [==============================] - 0s 8ms/step - loss: 0.1412 - accuracy: 1.0000
Epoch 172/200
1/1 [==============================] - 0s 7ms/step - loss: 0.1401 - accuracy: 1.0000
Epoch 173/200
1/1 [==============================] - 0s 8ms/step - loss: 0.1390 - accuracy: 1.0000
Epoch 174/200
1/1 [==============================] - 0s 7ms/step - loss: 0.1380 - accuracy: 1.0000
Epoch 175/200
1/1 [=====

Now that the model is trained, we will run it with sample input and see that it classifies correctly.

In [3]:
def runit(model, inp):
    inp = np.array(inp,dtype=np.float32)
    pred = model.predict(inp)
    return np.argmax(pred[0])

print( runit( model, [[[0],[1],[1],[0],[0],[0]]] ))


1


### Sun Spots Example - CNN

We now look at an example of CNN regression to predict sunspots.  You can find the data files needed for this example at the following location.

* [Sunspot Data Files](http://www.sidc.be/silso/datafiles#total)
* [Download Daily Sunspots](http://www.sidc.be/silso/INFO/sndtotcsv.php) - 1/1/1818 to now.

We use the following code to load the sunspot file:


In [4]:
import pandas as pd
import os

names = ['year', 'month', 'day', 'dec_year', 'sn_value' , 
         'sn_error', 'obs_num']
df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/SN_d_tot_V2.0.csv",
    sep=';',header=None,names=names,
    na_values=['-1'], index_col=False)

print("Starting file:")
print(df[0:10])

print("Ending file:")
print(df[-10:])

Starting file:
   year  month  day  dec_year  sn_value  sn_error  obs_num
0  1818      1    1  1818.001        -1       NaN        0
1  1818      1    2  1818.004        -1       NaN        0
2  1818      1    3  1818.007        -1       NaN        0
3  1818      1    4  1818.010        -1       NaN        0
4  1818      1    5  1818.012        -1       NaN        0
5  1818      1    6  1818.015        -1       NaN        0
6  1818      1    7  1818.018        -1       NaN        0
7  1818      1    8  1818.021        65      10.2        1
8  1818      1    9  1818.023        -1       NaN        0
9  1818      1   10  1818.026        -1       NaN        0
Ending file:
       year  month  day  dec_year  sn_value  sn_error  obs_num
72855  2017      6   21  2017.470        35       1.0       41
72856  2017      6   22  2017.473        24       0.8       39
72857  2017      6   23  2017.475        23       0.9       40
72858  2017      6   24  2017.478        26       2.3       15
72859  2

/Users/jeff/miniforge3/envs/tensorflow/lib/python3.9/site-packages/pandas/util/_decorators.py:311: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  return func(*args, **kwargs)


As you can see, there is quite a bit of missing data near the end of the file.  We want to find the starting index where the missing data no longer occurs.  This approach is somewhat sloppy; it would be better to find a use for the data between missing values.  However, the point of this example is to show how to use CNN with a somewhat simple time-series.

In [5]:
start_id = max(df[df['obs_num'] == 0].index.tolist())+1  # Find the last zero and move one beyond
print(start_id)
df = df[start_id:] # Trim the rows that have missing observations

11314


Next, we break the data into test and training sets.  We will train the neural network in the years before 2000 and test it with years after.

In [6]:
df['sn_value'] = df['sn_value'].astype(float)
df_train = df[df['year']<2000]
df_test = df[df['year']>=2000]

spots_train = df_train['sn_value'].tolist()
spots_test = df_test['sn_value'].tolist()

print("Training set has {} observations.".format(len(spots_train)))
print("Test set has {} observations.".format(len(spots_test)))

Training set has 55160 observations.
Test set has 6391 observations.


We will make use of the same **to_sequences** function previously used in this course.  This function allows us to convert the training and test data into the 2D sequences that will train the neural network. 

In [7]:
import numpy as np

def to_sequences(seq_size, obs):
    x = []
    y = []

    for i in range(len(obs)-SEQUENCE_SIZE-1):
        #print(i)
        window = obs[i:(i+SEQUENCE_SIZE)]
        after_window = obs[i+SEQUENCE_SIZE]
        window = [[x] for x in window]
        #print("{} - {}".format(window,after_window))
        x.append(window)
        y.append(after_window)
        
    return np.array(x),np.array(y)
    
    
SEQUENCE_SIZE = 25
x_train,y_train = to_sequences(SEQUENCE_SIZE,spots_train)
x_test,y_test = to_sequences(SEQUENCE_SIZE,spots_test)

print("Shape of training set: {}".format(x_train.shape))
print("Shape of test set: {}".format(x_test.shape))

Shape of training set: (55134, 25, 1)
Shape of test set: (6365, 25, 1)


We can display the training data, which is essentially a 2D matrix where each row is a sequence of the same length.

In [8]:
x_train

array([[[353.],
        [240.],
        [275.],
        ...,
        [270.],
        [289.],
        [308.]],

       [[240.],
        [275.],
        [352.],
        ...,
        [289.],
        [308.],
        [327.]],

       [[275.],
        [352.],
        [268.],
        ...,
        [308.],
        [327.],
        [323.]],

       ...,

       [[ 97.],
        [ 79.],
        [ 70.],
        ...,
        [128.],
        [116.],
        [ 95.]],

       [[ 79.],
        [ 70.],
        [ 87.],
        ...,
        [116.],
        [ 95.],
        [ 85.]],

       [[ 70.],
        [ 87.],
        [ 81.],
        ...,
        [ 95.],
        [ 85.],
        [103.]]])

We are now ready to build and train the neural network.  This code is similar to the previous classification example; however, now we are performing regression.  

In [9]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D
from tensorflow.keras.layers import Dropout, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np

print('Build model...')
model = Sequential()
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', 
                 input_shape=(SEQUENCE_SIZE,1)))
model.add(Conv1D(filters=32, kernel_size=3, activation='relu'))
model.add(Dropout(0.2))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=50, 
                        verbose=1, mode='auto', restore_best_weights=True)
print('Train...')

model.fit(x_train,y_train,validation_data=(x_test,y_test),
          callbacks=[monitor],verbose=2,epochs=1000)

Build model...
Train...
Epoch 1/1000
1723/1723 - 7s - loss: 1017.1534 - val_loss: 648.2256
Epoch 2/1000
1723/1723 - 7s - loss: 924.8314 - val_loss: 702.7062
Epoch 3/1000
1723/1723 - 7s - loss: 914.8549 - val_loss: 609.5417
Epoch 4/1000
1723/1723 - 6s - loss: 899.7807 - val_loss: 509.4393
Epoch 5/1000
1723/1723 - 7s - loss: 887.5994 - val_loss: 740.5092
Epoch 6/1000
1723/1723 - 7s - loss: 892.1801 - val_loss: 718.6553
Epoch 7/1000
1723/1723 - 7s - loss: 879.7798 - val_loss: 889.8149
Epoch 8/1000
1723/1723 - 6s - loss: 875.0635 - val_loss: 729.5891
Epoch 9/1000
1723/1723 - 6s - loss: 878.8755 - val_loss: 666.5909
Epoch 10/1000
1723/1723 - 6s - loss: 869.3765 - val_loss: 861.8528
Epoch 11/1000
1723/1723 - 6s - loss: 876.2190 - val_loss: 538.1008
Epoch 12/1000
1723/1723 - 6s - loss: 863.6840 - val_loss: 572.9426
Epoch 13/1000
1723/1723 - 6s - loss: 863.4714 - val_loss: 755.2368
Epoch 14/1000
1723/1723 - 6s - loss: 856.7681 - val_loss: 717.9911
Epoch 15/1000
1723/1723 - 6s - loss: 858.6828 

Finally, we evaluate the accuracy of the predictions.

In [10]:
from sklearn import metrics

# from sklearn import metrics
pred = model.predict(x_test)
score = np.sqrt(metrics.mean_squared_error(pred.flatten(),y_test))
print("Score (RMSE): {}".format(score))

Score (RMSE): 21.65250005197068
